# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the current directory contents (files and subdirectories) into the container at /app
COPY . /app

# Install any Python packages listed in the requirements.txt file
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Set the default command to run when the container starts, which is running app.py with Python
CMD ["python", "app.py"]
